const productsData = [
  {
    id: 1,
    name: 'Product 1',
    image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/30882f19-9bd0-4fcb-8d0b-0ccca260789e/jordan-stadium-90-shoes-0cSSz3.png",
    price: 55,
    discountPrice: 31,
    description: 'Description for product 1',
    sizes: { M: 5, L: 2, S: 0, XL: 1 },   
    gender: 'Female',
    type: 'T-shirt'
  },
  {
    id: 2,
    name: 'Product 2',
    image: "https://i.pinimg.com/236x/ba/dd/82/badd82c3e216ea14d3b6bdfbf1df1f51.jpg",
    price: 29,
    discountPrice: 23,
    description: 'Description for product 2',
    sizes: { M: 6, L: 0, S: 1, XL: 1 },   
    gender: 'Male',
    type: 'Jeans'
  },
  {
    id: 3,
    name: 'Product 3',
    image:"https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/72f311a4-d0c8-4563-816a-f7ff2f78be8a/jordan-stadium-90-older-shoes-2J5HrK.png",
    price: 91,
    discountPrice: 19,
    description: 'Description for product 3',
    sizes: { M: 1, L: 0, S: 1, XL: 1 },   
    gender: 'Female',
    type: 'Jeans'
  },
  {
    id: 4,
    name: 'Product 4',
    image:  "https://i.pinimg.com/236x/84/a8/4c/84a84c962b2ff1b02a0676b81fb2c281.jpg",
    price: 80,
    discountPrice: 10,
    description: 'Description for product 4',
    sizes: { M: 6, L: 0, S: 0, XL: 4 },   
    gender: 'Female',
    type: 'T-shirt'
  },
  {
    id: 5,
    name: 'Product 5',
    image:  "https://i.pinimg.com/236x/c6/b3/0d/c6b30d1e048c351d63499ea1c5d88c5c.jpg",
    price: 52,
    discountPrice: 25,
    description: 'Description for product 5',
    sizes: { M: 0, L: 1, S: 5, XL: 4 },   
    gender: 'Male',
    type: 'Jeans'
  },
  {
    id: 6,
    name: 'Product 6',
    image: "https://i.pinimg.com/236x/24/bd/69/24bd691c579d4a7b5bfa7d44792fa5dc.jpg",
    price: 32,
    discountPrice: 21,
    description: 'Description for product 6',
    sizes: { M: 5, L: 0, S: 1, XL: 4 },   
    gender: 'Children',
    type: 'Jeans'
  },
  {
    id: 7,
    name: 'Product 7',
    image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/yn3xyrwq1i8l6i5txngn/air-max-270-shoes-2V5C4p.png",
    price: 93,
    discountPrice: 22,
    description: 'Description for product 7',
    sizes: { M: 5, L: 0, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'Jeans'
  },
  {
    id: 8,
    name: 'Product 8',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1aedcf51-beac-4e7f-ba01-052ca16786e8/air-max-90-gore-tex-shoes-K3mBRb.png',
    price: 45,
    discountPrice: 22,
    description: 'Description for product 8',
    sizes: { M: 6, L: 3, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'Shirt'
  },
  {
    id: 9,
    name: 'Product 9',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/2da18722-5ac6-4e12-b30f-5b429b4c67a1/sb-zoom-blazer-low-pro-gt-skate-shoes-ckWK6g.png',
    price: 8,
    discountPrice: 9,
    description: 'Description for product 9',
    sizes: { M: 2, L: 1, S: 0, XL: 2 },   
    gender: 'Male',
    type: 'Jeans'
  },
  {
    id: 10,
    name: 'Product 10',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a18b5353-87cd-486b-a689-5369f7764e40/initiator-running-shoe-NRLxhm.png',
    price: 69,
    discountPrice: 28,
    description: 'Description for product 10',
    sizes: { M: 1, L: 0, S: 0, XL: 1 },   
    gender: 'Female',
    type: 'Shirt'
  },
  {
    id: 11,
    name: 'Product 11',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/ba08723a-a8e4-496e-b0f5-66436807076e/jumpman-mvp-shoes-JV1HCs.png',
    price: 64,
    discountPrice: 40,
    description: 'Description for product 11',
    sizes: { M: 2, L: 1, S: 0, XL: 2 },   
    gender: 'Female',
    type: 'Shirt'
  },
  {
    id: 12,
    name: 'Product 12',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/872ada20-8f75-4fdc-ab73-1a2aeace2307/jordan-one-take-4-pf-shoes-v5trdl.png',
    price: 90,
    discountPrice: 22,
    description: 'Description for product 12',
    sizes: { M: 5, L: 1, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'Shirt'
  },
  {
    id: 13,
    name: 'Product 13',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0dbef9d2-e69b-4df8-b52f-4e679d20e486/air-max-alpha-trainer-5-workout-shoes-x8Jzj6.png',
    price: 45,
    discountPrice: 50,
    description: 'Description for product 13',
    sizes: { M: 0, L: 1, S: 0, XL: 1 },   
    gender: 'Children',
    type: 'Shirt'
  },
  {
    id: 14,
    name: 'Product 14',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/ce38e3d4-7382-4d01-8984-3c5667f7e465/paris-saint-germain-jumpman-mvp-shoes-LxppNW.png',
    price: 25,
    discountPrice: 1,
    description: 'Description for product 14',
    sizes: { M: 0, L: 0, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'Shirt'
  },
  {
    id: 15,
    name: 'Product 15',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d8b84c50-0a61-4b66-8890-6ad1a3a17fd0/air-max-plus-shoes-mVwq4h.png',
    price: 56,
    discountPrice: 18,
    description: 'Description for product 15',
    sizes: { M: 3, L: 0, S: 0, XL: 2 },   
    gender: 'Male',
    type: 'Shirt'
  },
  {
    id: 16,
    name: 'Product 16',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9158ecfe-c60a-4463-8a9b-54d6773e2a18/air-max-2090-shoes-lqM65N.png',
    price: 9,
    discountPrice: 21,
    description: 'Description for product 16',
    sizes: { M: 5, L: 1, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'T-shirt'
  },
  {
    id: 17,
    name: 'Product 17',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/46e537d4-38f1-4ab6-86e3-9316a7450d43/metcon-9-workout-shoes-ldMsxB.png',
    price: 33,
    discountPrice: 40,
    description: 'Description for product 17',
    sizes: { M: 7, L: 1, S: 0, XL: 1 },   
    gender: 'Children',
    type: 'Shirt'
  },
  {
    id: 18,
    name: 'Product 18',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e3c549c7-0a3f-4ac2-b769-2f0ce8b26839/kd16-ep-basketball-shoes-ZX0HSQ.png',
    price: 27,
    discountPrice: 44,
    description: 'Description for product 18',
    sizes: { M: 0, L: 1, S: 0, XL: 5 },   
    gender: 'Female',
    type: 'T-shirt'
  },
  {
    id: 19,
    name: 'Product 19',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/91688d0a-77af-4fef-8e18-52932ada8e0b/superrep-go-3-next-nature-flyknit-workout-shoes-mxKptW.png',
    price: 86,
    discountPrice: 1,
    description: 'Description for product 19',
    sizes: { M: 5, L: 0, S: 0, XL: 1 },   
    gender: 'Male',
    type: 'T-shirt'
  },
  {
    id: 20,
    name: 'Product 20',
    image: 'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/24cad07c-d6c3-4303-bbb5-dfabc500826c/air-flight-huarache-shoes-6VK5m9.png',
    price: 65,
    discountPrice: 27,
    description: 'Description for product 20',
    sizes: { M: 0, L: 2, S: 5, XL: 2 },   
    gender: 'Female',
    type: 'Shirt'
  },
  // {
  //   id: 21,
  //   name: 'Product 21',
  //   image: 'image_21.jpg',
  //   price: 14,
  //   discountPrice: 19,
  //   description: 'Description for product 21',
  //   sizes: { M: 1, L: 1, S: 2, XL: 3 },   
  //   gender: 'Male',
  //   type: 'Jeans'
  // },
  // {
  //   id: 22,
  //   name: 'Product 22',
  //   image: 'image_22.jpg',
  //   price: 87,
  //   discountPrice: 30,
  //   description: 'Description for product 22',
  //   sizes: { M: 2, L: 4, S: 3, XL: 1 },   
  //   gender: 'Children',
  //   type: 'Shirt'
  // },
  // {
  //   id: 23,
  //   name: 'Product 23',
  //   image: 'image_23.jpg',
  //   price: 8,
  //   discountPrice: 13,
  //   description: 'Description for product 23',
  //   sizes: { M: 1, L: 0, S: 0, XL: 2 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 24,
  //   name: 'Product 24',
  //   image: 'image_24.jpg',
  //   price: 63,
  //   discountPrice: 32,
  //   description: 'Description for product 24',
  //   sizes: { M: 1, L: 0, S: 1, XL: 1 },   
  //   gender: 'Children',
  //   type: 'T-shirt'
  // },
  // {
  //   id: 25,
  //   name: 'Product 25',
  //   image: 'image_25.jpg',
  //   price: 93,
  //   discountPrice: 1,
  //   description: 'Description for product 25',
  //   sizes: { M: 4, L: 4, S: 0, XL: 2 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 26,
  //   name: 'Product 26',
  //   image: 'image_26.jpg',
  //   price: 92,
  //   discountPrice: 1,
  //   description: 'Description for product 26',
  //   sizes: { M: 1, L: 0, S: 3, XL: 2 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 27,
  //   name: 'Product 27',
  //   image: 'image_27.jpg',
  //   price: 99,
  //   discountPrice: 14,
  //   description: 'Description for product 27',
  //   sizes: { M: 5, L: 1, S: 0, XL: 1 },   
  //   gender: 'Children',
  //   type: 'Shirt'
  // },
  // {
  //   id: 28,
  //   name: 'Product 28',
  //   image: 'image_28.jpg',
  //   price: 22,
  //   discountPrice: 9,
  //   description: 'Description for product 28',
  //   sizes: { M: 0, L: 1, S: 0, XL: 1 },   
  //   gender: 'Children',
  //   type: 'T-shirt'
  // },
  // {
  //   id: 29,
  //   name: 'Product 29',
  //   image: 'image_29.jpg',
  //   price: 75,
  //   discountPrice: 10,
  //   description: 'Description for product 29',
  //   sizes: { M: 6, L: 1, S: 0, XL: 1 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 30,
  //   name: 'Product 30',
  //   image: 'image_30.jpg',
  //   price: 18,
  //   discountPrice: 32,
  //   description: 'Description for product 30',
  //   sizes: { M: 2, L: 0, S: 0, XL: 8 },   
  //   gender: 'Children',
  //   type: 'Jeans'
  // },
  // {
  //   id: 31,
  //   name: 'Product 31',
  //   image: 'image_31.jpg',
  //   price: 72,
  //   discountPrice: 48,
  //   description: 'Description for product 31',
  //   sizes: { M: 3, L: 5, S: 0, XL: 2 },   
  //   gender: 'Children',
  //   type: 'Jeans'
  // },
  // {
  //   id: 32,
  //   name: 'Product 32',
  //   image: 'image_32.jpg',
  //   price: 66,
  //   discountPrice: 18,
  //   description: 'Description for product 32',
  //   sizes: { M: 2, L: 0, S: 0, XL: 1 },   
  //   gender: 'Female',
  //   type: 'T-shirt'
  // },
  // {
  //   id: 33,
  //   name: 'Product 33',
  //   image: 'image_33.jpg',
  //   price: 92,
  //   discountPrice: 49,
  //   description: 'Description for product 33',
  //   sizes: { M: 2, L: 0, S: 0, XL: 1 },   
  //   gender: 'Children',
  //   type: 'Shirt'
  // },
  // {
  //   id: 34,
  //   name: 'Product 34',
  //   image: 'image_34.jpg',
  //   price: 67,
  //   discountPrice: 6,
  //   description: 'Description for product 34',
  //   sizes: { M: 0, L: 4, S: 2, XL: 2 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 35,
  //   name: 'Product 35',
  //   image: 'image_35.jpg',
  //   price: 55,
  //   discountPrice: 33,
  //   description: 'Description for product 35',
  //   sizes: { M: 2, L: 0, S: 1, XL: 3 },   
  //   gender: 'Children',
  //   type: 'Jeans'
  // },
  // {
  //   id: 36,
  //   name: 'Product 36',
  //   image: 'image_36.jpg',
  //   price: 73,
  //   discountPrice: 30,
  //   description: 'Description for product 36',
  //   sizes: { M: 0, L: 0, S: 0, XL: 1 },   
  //   gender: 'Children',
  //   type: 'Jeans'
  // },
  // {
  //   id: 37,
  //   name: 'Product 37',
  //   image: 'image_37.jpg',
  //   price: 57,
  //   discountPrice: 23,
  //   description: 'Description for product 37',
  //   sizes: { M: 2, L: 6, S: 1, XL: 1 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 38,
  //   name: 'Product 38',
  //   image: 'image_38.jpg',
  //   price: 41,
  //   discountPrice: 27,
  //   description: 'Description for product 38',
  //   sizes: { M: 1, L: 0, S: 1, XL: 1 },   
  //   gender: 'Female',
  //   type: 'T-shirt'
  // },
  // {
  //   id: 39,
  //   name: 'Product 39',
  //   image: 'image_39.jpg',
  //   price: 95,
  //   discountPrice: 11,
  //   description: 'Description for product 39',
  //   sizes: { M: 3, L: 4, S: 0, XL: 2 },   
  //   gender: 'Male',
  //   type: 'Shirt'
  // },
  // {
  //   id: 40,
  //   name: 'Product 40',
  //   image: 'image_40.jpg',
  //   price: 38,
  //   discountPrice: 5,
  //   description: 'Description for product 40',
  //   sizes: { M: 0, L: 0, S: 0, XL: 2 },   
  //   gender: 'Female',
  //   type: 'Jeans'
  // }
]
module.exports = productsData;
